name: Kotlin Frontend CI Workflow

# Controls when the workflow will run
on:
  # Allows us to call this workflow within another workflow
  workflow_call:
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggered based on the git event type
  push:
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2.3.2
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: 11
      # Build the app
      - name: Build with Gradle
        run: ./gradlew build
        run: |
          ./gradlew build
      # Debug Unit Tests
      - name: Debug Unit Tests
        run: |
          ./gradlew testDebugUnitTest
      # Run Tests
      - name: Run Tests
        run: |
          ./gradlew test
      # Run a linter
      - name: Run Lint
        run: |
          ./gradlew Lint
